# Generated by Django 3.1.7 on 2021-04-04 14:01

import django.core.validators
from django.db import migrations
import imagekit.models.fields
import solf.apps.classes.models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=solf.apps.classes.models.Class.class_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'heic', 'svg'])], verbose_name='Class Image'),
        ),
    ]
