# Generated by Django 3.1.7 on 2021-04-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassScheduleLogs',
            new_name='ClassLogs',
        ),
    ]
