# Generated by Django 3.1.7 on 2021-04-12 17:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userpass'),
        ('classes', '0003_auto_20210412_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('max_spots', models.PositiveSmallIntegerField(verbose_name='Maximum available spots')),
                ('entry_type', models.CharField(choices=[('BOOKING', 'In app booking'), ('CALLING', 'Phone call')], default='BOOKING', max_length=20, verbose_name='Entry Type')),
                ('class_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classlog', to='classes.class', verbose_name='Class')),
            ],
            options={
                'verbose_name': 'Class Logs',
                'verbose_name_plural': 'Classes Logs',
            },
        ),
        migrations.CreateModel(
            name='ClassUserEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('log', models.ForeignKey(blank=True, help_text='passed class', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entries', to='classes.classlog', verbose_name='Log')),
            ],
            options={
                'verbose_name': 'User Entry',
                'verbose_name_plural': 'User Entries',
            },
        ),
        migrations.AddField(
            model_name='classschedule',
            name='entry_type',
            field=models.CharField(choices=[('BOOKING', 'In app booking'), ('CALLING', 'Phone call')], default='BOOKING', max_length=20, verbose_name='Entry Type'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='class_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classschedule', to='classes.class', verbose_name='Class'),
        ),
        migrations.DeleteModel(
            name='ClassLogs',
        ),
        migrations.AddField(
            model_name='classuserentry',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='upcoming class', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entries', to='classes.classschedule', verbose_name='Schedule'),
        ),
        migrations.AddField(
            model_name='classuserentry',
            name='user_pass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entries', to='users.userpass', verbose_name='User Pass'),
        ),
        migrations.AddField(
            model_name='classlog',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='classes.classschedule', verbose_name='Schedule'),
        ),
    ]
