# Generated by Django 3.1.7 on 2021-05-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20210412_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active?'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active?'),
        ),
        migrations.AddField(
            model_name='classuserentry',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('CANCELED_BY_USER', 'Canceled by user'), ('CANCELED_BY_MODERATOR', 'Canceled by moderator'), ('MISSED', 'Missed'), ('APPROVED', 'Approved successfully')], default='WAITING', max_length=30, verbose_name='Entry Type'),
        ),
    ]
